on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Cache Flutter dependencies
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: flutter-packages-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            flutter-packages-${{ runner.os }}-

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.1
          token: ${{ secrets.TOKEN }}
          name: "stable-v1.0.1"
          body: |
            ## What's New in v1.0.1
            
            - **UI Fixtures**
            - **Hardware Onboarding Slider functionality**
            - **Supabase Auth Flow Integration Complete**
            - **Minor Bug fixes**
            - **Crash Handlers are improved**
            - **Improved Overall Performance - Implemented Impeller**
            
            ### Issues are being Resolved - P0 Integrations